services:
  ip-notify:
    build:
      context: .
    container_name: ip-notify
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      # The service webhook url. Include here or in .env file
      WEBHOOK_URL: "${WEBHOOK_URL}"
      # Service name discord|msteams
      WEBHOOK_SERVICE: "discord"
      # Cron expression used by supercronic
      SCHEDULE: "${SCHEDULE:-*/1 * * * *}"
      # The color of the Discord Embed in hex
      EMBED_COLOR: "1bb106"
      # The link when clicking the Embed author
      AUTHOR_URL: "https://codeberg.org/jack-mil/ip-notify"
      # # Time Zone for logs
      TZ: "America/New_York"
